* CBC_VIDEO
  CBC [[http://www.cbc.ca/player/][web player]] does not provide direct MP4 urls, however they can be queried directly from:
  [[http://feed.theplatform.com/f/h9dtGB/r3VD0FujBumK?%2527%2B%2522&form%3Djson&range%3D1-100][http://feed.theplatform.com/f/h9dtGB/r3VD0FujBumK?%27+%22&form=json&range=1-100]]

  This simply queries the URL (from the client browser) and parses the results.

* Technology

** Server
  - [[https://nodejs.org/en/][Node js]]
  - [[http://expressjs.com/][Express js]]
  - [[http://paularmstrong.github.io/swig/][swig]] ( templating )

** Client
  - [[http://getbootstrap.com/][bootstrap]]
  - [[https://jquery.com/][jQuery]]
  - [[http://handlebarsjs.com/][handlebars js]] ( templating )

* Install

** web client
  While this doesn't HAVE to be run from Node for development reasons it express was used.
  Other reason is to beable to deploy the code to Heroku.

  Typical Node/express setup:

  #+BEGIN_SRC sh
  $ git clone git@github.com:jjrh/CBC_VIDEO.git
  $ cd CBC_VIDEO
  $ npm install
  $ ./run_server.sh 3030
  #+END_SRC

  For the most part CDN's have been used for libraries.

** standalone application
   Stand alone application could use some work and user will need to edit source to include shows.
   Currently setup for

   - Power and Politics
   - the nature of things
   - The National - Full Show
   - The Exchange with Amanda Lang
   - THE FIFTH ESTATE


   #+BEGIN_SRC
   $ git clone git@github.com:jjrh/CBC_VIDEO.git
   $ cd CBC_VIDEO
   $ npm install request
   $ node get_videos.js
   #+END_SRC



* credits / references
  Credit to this person who made tracking down the right URLs much easier.
  - http://cbcvideocontentconnector.appspot.com/
  - https://github.com/misener/CBC-Content-Connector


  And obviously credit to the [[http://www.CBC.ca][CBC]]!

  - http://www.cbc.ca/player/
